### ISSUE TITLE
About the Project 

### ISSUE THREAD

**Issue by farrakhanwahab** [farrakhanwahab/Group-Work#1]
So how do we start? Which unit do you think we should work on? Any ideas?

**Comment by Gyapon** [comment]
I suggest we use the GIMPA Instructional Resource Centre.

**Comment by esrbh** [comment]
Sure, I'm totally on board with that idea!. Just to clarify they are in charge of handling the projectors and also printing id cards right? 
We'll need to find out what their current issues are.

**Comment by Gyapon** [comment]
I think the issues with the unit now is the old hdmi,vga cables in almost all the lecture halls on campus.

**Comment by Michael-rob** [comment]
We could discuss future plans or developments for the center to further enhance its offerings.

**Comment by farrakhanwahab** [comment]
Okay so we have some issues but what will be the problem?

**Comment by farrakhanwahab** [comment]
Remember we have to find series of problems and then narrow it down to one problem so we can solve it easily

**Comment by Gyapon** [comment]
The problems at the unit is many, if we should mention all time will defeat us Farrakan! but we can take you through some of the problems at the unit, that need a critical attention and solutions is the projectors and the hdmi and the vga cables. So if we can get a software for the projectors to connect to the laptops so we do away with the cable connection?

**Comment by farrakhanwahab** [comment]
Hmmm🤔
Good idea but on Monday let's get our 15 questions

**Comment by esrbh** [comment]
Sounds like a plan.👍🏽 
Monday after class we can all head down there. But our aim should be at least 15 questions.

**Comment by Gyapon** [comment]
I think we should prepare  the fifteen questions we are to ask the unit down before we get to the office.

**Comment by farrakhanwahab** [comment]
Any ideas? 
Anyone?

**Comment by esrbh** [comment]
Our aim there is to get 15 problems not ask them 15 questions. 
So we ask them what issues they are currently facing and they'll list it down for us, hopefully 15 or more. After which we pick one and try to solve it.

**Comment by farrakhanwahab** [comment]
Wait! 
Was it questions or problems??

**Comment by esrbh** [comment]
Problems. 
We focus on one, solve and implement a system before 11th March. Please guys let's get this right.

**Comment by Michael-rob** [comment]
> Problems. 
> We focus on one, solve and implement a system before 11th March. Please guys let's get this right. 

Alright sure ✌️

**Comment by farrakhanwahab** [comment]
> Problems. 
> We focus on one, solve and implement a system before 11th March. Please guys let's get this right. 


Ei😂

**Comment by farrakhanwahab** [comment]
I thought it was questions

**Comment by Michael-rob** [comment]
> I thought it was questions 

Nah it's problems

**Comment by farrakhanwahab** [comment]
Alright then
