### ISSUE TITLE
Questions & Problems at IRC

### ISSUE THREAD

**Issue by farrakhanwahab** [farrakhanwahab/Group-Work#2]

**Comment by farrakhanwahab** [comment]
So now we know the numerous problems at IRC and why the IRC exits in the first place

**Comment by farrakhanwahab** [comment]
Out of all their problems; being projector problems, markers and duster problems, cable problems, white boards problems, PA systems and many more. 
We got to see that the root cause of these problems boil down to bad leadership. 
Since we cannot fix bad leadership with IT let's all select the easiest of these problems and fix it with IT

**Comment by Michael-rob** [comment]
Let's deal projector problems

**Comment by Michael-rob** [comment]
Let's deal with projector problems

**Comment by Gyapon** [comment]
I suggest we focus on the projector problem, since management is refusing to buy new cables to replace the old and the faulty ones.

**Comment by farrakhanwahab** [comment]
Okay 
We're 4 so let's each generate 4 questions each then we'll go back to IRC and ask our questions based on the projector problems

**Comment by esrbh** [comment]
Alright. 

1.What are the most common issues encountered when setting up projectors for presentations or meetings?

2.Are there any recurring problems with projector connectivity, such as HDMI or VGA issues?

3.Are there specific rooms or locations where projector issues occur more frequently, and if so, what factors contribute to these problems?

4.Are there any compatibility issues between projectors and different devices or operating systems?

**Comment by Gyapon** [comment]
1. How often do you encounter issues with the projectors during presentations or meetings?

2. Can you describe the most common problems you face with the projectors, such as connectivity issues, image quality, or hardware malfunctions?

3. Are there any specific areas where you feel the current projector setup is lacking or could be improved to enhance efficiency and performance?

4. How do you currently troubleshoot projector problems, and do you feel that there is a need for additional training or resources to address these issues effectively?

**Comment by farrakhanwahab** [comment]
Mike we are waiting for your questions!

**Comment by farrakhanwahab** [comment]
1. How might external environmental factors, such as room temperature or humidity, affect the projector's performance?
2. How does the power supply and electrical infrastructure impact the projector's functioning?
3. How do user interactions and settings influence the projector's behavior and potential issues?
4. ⁠Are there systemic issues related to the projector's maintenance or lack thereof?

**Comment by farrakhanwahab** [comment]
Tomorrow we'll ask our questions
We have 16 questions in total

**Comment by Gyapon** [comment]
Good evening guys please hope we're all fine? Tomorrow can we make it to the IRC to ask our questions?

**Comment by farrakhanwahab** [comment]
Yes

**Comment by farrakhanwahab** [comment]
Tomorrow after class

**Comment by farrakhanwahab** [comment]
We have to do the implementation this week too

**Comment by esrbh** [comment]
Yeah that's true. Let's ask our questions tomorrow

**Comment by Gyapon** [comment]
Good morning team and happy Easter to you all!!

**Comment by Gyapon** [comment]
Implementing wireless dongles for presentation displays has become a popular choice for businesses and individuals seeking a convenient and efficient way to share content during meetings and presentations. By eliminating the need for tangled cables and allowing users to connect their devices wirelessly to a display, these dongles offer flexibility and ease of use.

This report aims to explore the benefits and challenges of using wireless dongles for presentation displays. We will discuss the rationale behind adopting this technology, analyze its impact on productivity, and provide recommendations for successful implementation. Additionally, we will examine the current market trends and the key factors to consider when choosing a wireless dongle for your presentation needs.

Can we throw some on the implementation part of the project?

**Comment by farrakhanwahab** [comment]
Ignatius this is the wrong place o

**Comment by Gyapon** [comment]
**Title:** Formal Project Report: Implementation of Wireless Dongles

**Executive Summary:**
This formal project report details the successful deployment of wireless dongles as a replacement for HDMI and VGA cables for presentation displays. The report provides insights into the project's objectives, methodology, findings, and associated costs.

**Table of Contents:**
1. Introduction
2. Project Objectives
3. Project Scope
4. Methodology
5. Implementation Process
6. Findings and Results
7. Cost Analysis
8. Benefits and Challenges
9. Recommendations
10. Conclusion
11. References
12. Appendices

**1. Introduction:**
Introduces the project, outlining the rationale behind implementing wireless dongles for presentation displays and providing an overview of the report.

**2. Project Objectives:**
States the specific goals and objectives of the project, including enhancing presentation flexibility, reducing cable clutter, and improving user experience.

**3. Project Scope:**
Defines the scope of the project, including the targeted areas for implementation and the timeline for deployment.

**4. Methodology:**
Describes the approach taken to research, select, and procure wireless dongles, as well as the strategy for installation and user training.

**5. Implementation Process:**
Details the step-by-step process of implementing wireless dongles across the organization, including any challenges faced and solutions employed.

**6. Findings and Results:**
Presents the findings of the project, such as user feedback, technical performance evaluations, and overall satisfaction levels.

**7. Cost Analysis:**
Breaks down the costs associated with the implementation, including expenses for purchasing wireless dongles, installation, training, and any additional equipment or services required.

**8. Benefits and Challenges:**
Discusses the benefits realized from adopting wireless dongles for presentation displays, such as increased mobility, reduced setup time, and enhanced collaboration, as well as any challenges encountered during the implementation process.

**9. Recommendations:**
Provides recommendations for future improvements or adjustments based on the project's findings and experiences.

**10. Conclusion:**
Summarizes the key findings and outcomes of the project, emphasizing its success in achieving the stated objectives.

**11. References:**
Lists all sources cited throughout the report.

**12. Appendices:**
Includes supplementary materials such as cost breakdowns, technical specifications, user manuals, and any additional documentation relevant to the project.

**Comment by Gyapon** [comment]
Please let's start with the implementation stage?

**Comment by farrakhanwahab** [comment]
This isn't where we're handling the report process. Please check well before you put the info
